name: CI/CD with Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: your-docker-repo
          tag_with_ref: true

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@main
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy your-service \
            --image your-docker-repo \
            --platform managed \
            --region $REGION
        env:
          REGION: us-central1
